#!/bin/sh

fetch() {
  case $# in
    1) curl --location --remote-name "$1" ;;
    2) curl --location "$1" --output "$2" ;;
  esac
}

mkdir -p packages
cd packages

fetch https://github.com/FortAwesome/Font-Awesome/raw/master/svgs/solid/edit.svg
fetch https://i.imgur.com/uw1fOR7.png edit.png
